### PR TITLE
Unknown column 'cruser_id' in 'field list'

### PR DESCRIPTION
**Pull request by ste101**
Version 3.0.1

table_local seem to be wrong also.

### CODE REVIEW

**Comment by itx-benjamin-jasper** [comment]
I can't really reproduce this, my table has these fields defined, any ideas why you don't have them?

**Comment by ste101** [comment]
In V12 these fields don't exists anymore.
Did you check the database analyser?

**Comment by itx-benjamin-jasper** [comment]
Oh yes you are totally right, my bad

**Comment by ste101** [comment]
'table_local' does not exist also.

**Comment by itx-benjamin-jasper** [comment]
yeah i saw https://github.com/itx-informationssysteme/jobapplications/commit/70ebf05c2cda99d2850f9e6e82f640ebc6099cc1

**Pull request merged**
